# Generated by Django 5.0.6 on 2024-10-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_email_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email_Account',
        ),
    ]
